<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>a91d12cd-de62-4880-a452-eb8e4189ed79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='Province']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;Province&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Province</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                      เลือกจังหวัด...


                       กรุงเทพมหานคร 
                       กระบี่ 
                       กาญจนบุรี 
                       กาฬสินธุ์ 
                       กำแพงเพชร 
                       ขอนแก่น 
                       จันทบุรี 
                       ฉะเชิงเทรา 
                       ชลบุรี 
                       ชัยนาท 
                       ชัยภูมิ 
                       ชุมพร 
                       เชียงราย 
                       เชียงใหม่ 
                       ตรัง 
                       ตราด 
                       ตาก 
                       นครนายก 
                       นครปฐม 
                       นครพนม 
                       นครราชสีมา 
                       นครศรีธรรมราช 
                       นครสวรรค์ 
                       นนทบุรี 
                       นราธิวาส 
                       น่าน 
                       บึงกาฬ 
                       บุรีรัมย์ 
                       ปทุมธานี 
                       ประจวบคีรีขันธ์ 
                       ปราจีนบุรี 
                       ปัตตานี 
                       พระนครศรีอยุธยา 
                       พังงา 
                       พัทลุง 
                       พิจิตร 
                       พิษณุโลก 
                       เพชรบุรี 
                       เพชรบูรณ์ 
                       แพร่ 
                       พะเยา 
                       ภูเก็ต 
                       มหาสารคาม 
                       มุกดาหาร 
                       แม่ฮ่องสอน 
                       ยะลา 
                       ยโสธร 
                       ร้อยเอ็ด 
                       ระนอง 
                       ระยอง 
                       ราชบุรี 
                       ลพบุรี 
                       ลำปาง 
                       ลำพูน 
                       เลย 
                       ศรีสะเกษ 
                       สกลนคร 
                       สงขลา 
                       สตูล 
                       สมุทรปราการ 
                       สมุทรสงคราม 
                       สมุทรสาคร 
                       สระแก้ว 
                       สระบุรี 
                       สิงห์บุรี 
                       สุโขทัย 
                       สุพรรณบุรี 
                       สุราษฎร์ธานี 
                       สุรินทร์ 
                       หนองคาย 
                       หนองบัวลำภู 
                       อ่างทอง 
                       อุดรธานี 
                       อุทัยธานี 
                       อุตรดิตถ์ 
                       อุบลราชธานี 
                       อำนาจเจริญ 
                  </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-md-6 col-lg-6&quot;]/div[@class=&quot;login-wrap p-0&quot;]/form[@class=&quot;signin-form&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/select[@class=&quot;form-control select&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='Province']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='จังหวัด'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='อำเภอ'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สถานภาพการทำงาน'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ทำงานแล้ว'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Province' and (text() = '
                      เลือกจังหวัด...


                       กรุงเทพมหานคร 
                       กระบี่ 
                       กาญจนบุรี 
                       กาฬสินธุ์ 
                       กำแพงเพชร 
                       ขอนแก่น 
                       จันทบุรี 
                       ฉะเชิงเทรา 
                       ชลบุรี 
                       ชัยนาท 
                       ชัยภูมิ 
                       ชุมพร 
                       เชียงราย 
                       เชียงใหม่ 
                       ตรัง 
                       ตราด 
                       ตาก 
                       นครนายก 
                       นครปฐม 
                       นครพนม 
                       นครราชสีมา 
                       นครศรีธรรมราช 
                       นครสวรรค์ 
                       นนทบุรี 
                       นราธิวาส 
                       น่าน 
                       บึงกาฬ 
                       บุรีรัมย์ 
                       ปทุมธานี 
                       ประจวบคีรีขันธ์ 
                       ปราจีนบุรี 
                       ปัตตานี 
                       พระนครศรีอยุธยา 
                       พังงา 
                       พัทลุง 
                       พิจิตร 
                       พิษณุโลก 
                       เพชรบุรี 
                       เพชรบูรณ์ 
                       แพร่ 
                       พะเยา 
                       ภูเก็ต 
                       มหาสารคาม 
                       มุกดาหาร 
                       แม่ฮ่องสอน 
                       ยะลา 
                       ยโสธร 
                       ร้อยเอ็ด 
                       ระนอง 
                       ระยอง 
                       ราชบุรี 
                       ลพบุรี 
                       ลำปาง 
                       ลำพูน 
                       เลย 
                       ศรีสะเกษ 
                       สกลนคร 
                       สงขลา 
                       สตูล 
                       สมุทรปราการ 
                       สมุทรสงคราม 
                       สมุทรสาคร 
                       สระแก้ว 
                       สระบุรี 
                       สิงห์บุรี 
                       สุโขทัย 
                       สุพรรณบุรี 
                       สุราษฎร์ธานี 
                       สุรินทร์ 
                       หนองคาย 
                       หนองบัวลำภู 
                       อ่างทอง 
                       อุดรธานี 
                       อุทัยธานี 
                       อุตรดิตถ์ 
                       อุบลราชธานี 
                       อำนาจเจริญ 
                  ' or . = '
                      เลือกจังหวัด...


                       กรุงเทพมหานคร 
                       กระบี่ 
                       กาญจนบุรี 
                       กาฬสินธุ์ 
                       กำแพงเพชร 
                       ขอนแก่น 
                       จันทบุรี 
                       ฉะเชิงเทรา 
                       ชลบุรี 
                       ชัยนาท 
                       ชัยภูมิ 
                       ชุมพร 
                       เชียงราย 
                       เชียงใหม่ 
                       ตรัง 
                       ตราด 
                       ตาก 
                       นครนายก 
                       นครปฐม 
                       นครพนม 
                       นครราชสีมา 
                       นครศรีธรรมราช 
                       นครสวรรค์ 
                       นนทบุรี 
                       นราธิวาส 
                       น่าน 
                       บึงกาฬ 
                       บุรีรัมย์ 
                       ปทุมธานี 
                       ประจวบคีรีขันธ์ 
                       ปราจีนบุรี 
                       ปัตตานี 
                       พระนครศรีอยุธยา 
                       พังงา 
                       พัทลุง 
                       พิจิตร 
                       พิษณุโลก 
                       เพชรบุรี 
                       เพชรบูรณ์ 
                       แพร่ 
                       พะเยา 
                       ภูเก็ต 
                       มหาสารคาม 
                       มุกดาหาร 
                       แม่ฮ่องสอน 
                       ยะลา 
                       ยโสธร 
                       ร้อยเอ็ด 
                       ระนอง 
                       ระยอง 
                       ราชบุรี 
                       ลพบุรี 
                       ลำปาง 
                       ลำพูน 
                       เลย 
                       ศรีสะเกษ 
                       สกลนคร 
                       สงขลา 
                       สตูล 
                       สมุทรปราการ 
                       สมุทรสงคราม 
                       สมุทรสาคร 
                       สระแก้ว 
                       สระบุรี 
                       สิงห์บุรี 
                       สุโขทัย 
                       สุพรรณบุรี 
                       สุราษฎร์ธานี 
                       สุรินทร์ 
                       หนองคาย 
                       หนองบัวลำภู 
                       อ่างทอง 
                       อุดรธานี 
                       อุทัยธานี 
                       อุตรดิตถ์ 
                       อุบลราชธานี 
                       อำนาจเจริญ 
                  ')]</value>
   </webElementXpaths>
</WebElementEntity>
